#!/bin/bash

METHOD="POST"

while getopts "C:A:E:G" opt; do
  case $opt in
  C)
    API_CALL="${OPTARG}"
    ;;
  A)
    API_CALL_ARGUMENTS="${OPTARG}"
    ;;
  E)
    JQ_EXPRESSION="${OPTARG}"
    ;;
  G)
    METHOD="GET"
    ;;
  esac
done

if RESPONSE="$(curl -Ls -X "${METHOD}" "http://127.0.0.1:5000/api/${API_CALL}?${API_CALL_ARGUMENTS}")"; then
  if jq -r . <<<"${RESPONSE}" &>/dev/null; then
    SUCCESS="$(jq -r ".success" <<<"$RESPONSE")"
    MESSAGE="$(jq -r ".message" <<<"${RESPONSE}")"

    echo -e "\033[1;97;4m${MESSAGE}\033[0m:\n"

    if [ "${SUCCESS}" -ne 1 ]; then
      ERROR_MESSAGE="\033[1m$(jq -r ".data.error.codeMessage" <<<"${RESPONSE}")\033[0m: $(jq -r ".data.error.details" <<<"${RESPONSE}")"
      echo -e " -> ${ERROR_MESSAGE}"
    else
      SUCCESS_MESSAGE="$(jq -r "${JQ_EXPRESSION:-.}" <<<"${RESPONSE}")"
      echo -e "${SUCCESS_MESSAGE}"
    fi

    echo
  else
    echo -e "${RESPONSE}"
  fi
else
  echo "CURL failed"
fi
