#!/bin/bash

ANSI_BLACK="\e[30m"
ANSI_BLACK_BACKGROUND="\e[40m"
ANSI_RED="\e[31m"
ANSI_RED_BACKGROUND="\e[41m"
ANSI_GREEN="\e[32m"
ANSI_GREEN_BACKGROUND="\e[42m"
ANSI_BROWN="\e[33m"
ANSI_BROWN_BACKGROUND="\e[43m"
ANSI_BLUE="\e[34m"
ANSI_BLUE_BACKGROUND="\e[44m"
ANSI_PURPLE="\e[35m"
ANSI_PURPLE_BACKGROUND="\e[45m"
ANSI_CYAN="\e[36m"
ANSI_CYAN_BACKGROUND="\e[46m"
ANSI_GREY="\e[37m"
ANSI_GREY_BACKGROUND="\e[47m"

## Style
ANSI_BOLD="\e[1m"
ANSI_ITALIAN="\e[3m"
ANSI_UNDERLINE="\e[4m"
ANSI_BLINK="\e[5m"
ANSI_REVERSED_VIDEO="\e[7m"
ANSI_STRIKETHROUGH="\e[9m"
ANSI_END="\e[0m"

echo -e "\n
${ANSI_BOLD}════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════${ANSI_END}
${ANSI_BOLD}${ANSI_BLUE}
                                                                                          ▒▒            
                                                                      ░░    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒▒          
                                                                      ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒        
                                                                      ▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓  ▒▒▒▒        
                                                  ████                ▒▒▒▒    ░░        ▓▓▓▓▒▒▒▒▓▓      
                                                    ██                ▒▒▒▒▓▓▓▓░░▓▓░░▓▓░░░░░░    ▒▒      
                                                                      ▒▒░░░░░░░░░░▓▓░░░░░░░░░░░░░░      
                                                                        ░░░░░░░░░░░░░░░░░░░░░░░░░░      
                                                                      ░░░░░░░░░░░░░░░░░░░░░░░░░░        
                                  ▒▒▓▓▓▓                                ░░░░░░░░░░░░░░░░░░░░░░          
                                ▓▓▓▓▓▓▓▓                              ▓▓▓▓▒▒░░░░░░░░░░░░░░▒▒▓▓          
                                ▓▓▓▓▓▓▓▓        ░░                  ░░▒▒▓▓▓▓░░▒▒▒▒▒▒▒▒▒▒▓▓▓▓▒▒          
                                ▓▓▓▓▓▓▓▓▒▒  ▒▒▒▒▒▒▒▒                ▒▒▒▒▒▒▓▓▒▒▒▒▒▒▒▒░░▓▓▓▓▒▒▒▒          
                                ▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓  ▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒          
                                  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░▒▒▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒          
                                  ▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓▒▒▒▒▓▓▒▒░░▒▒░░  ▓▓▒▒▒▒▒▒▓▓▓▓▒▒▒▒          
                                    ▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒░░▒▒▓▓▒▒▒▒▒▒▓▓▓▓░░░░▒▒            
                                    ▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒▒▒▓▓░░▒▒            
                                      ▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒              
                                      ▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒                
                                          ▒▒▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░▒▒▒▒▒▒░░░░                  
                          ▓▓                  ▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░▒▒▒▒░░░░                    
                          ▓▓▓▓                    ▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▒▒░░                        
                          ▒▒▓▓▓▓▓▓                ▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░                          
                            ▓▓▓▓▓▓▓▓▒▒        ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░                              
                            ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓                                    
                                ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓                                            
                                    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒                                                




                        ██████╗██╗  ██╗██████╗  ██████╗ ███╗   ██╗██╗ ██████╗██╗     ███████╗
                        ██╔════╝██║  ██║██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝██║     ██╔════╝
                        ██║     ███████║██████╔╝██║   ██║██╔██╗ ██║██║██║     ██║     █████╗  
                        ██║     ██╔══██║██╔══██╗██║   ██║██║╚██╗██║██║██║     ██║     ██╔══╝  
                        ╚██████╗██║  ██║██║  ██║╚██████╔╝██║ ╚████║██║╚██████╗███████╗███████╗
                        ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝╚══════╝╚══════╝

${ANSI_END}
${ANSI_BOLD}════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════${ANSI_END}\n"

function inform {
  TYPE="$1"
  shift
  case "$TYPE" in
  0)
    echo -e " ${ANSI_BOLD}${ANSI_CYAN}[-]${ANSI_END} ${ANSI_BOLD}[SERVICE_]:${ANSI_END} $*"
    ;;
  1)
    echo -e " ${ANSI_BOLD}${ANSI_BROWN}[*]${ANSI_END} ${ANSI_BOLD}[SERVICE_]:${ANSI_END} $*"
    ;;
  2)
    echo -e " ${ANSI_BOLD}${ANSI_RED}[!]${ANSI_END} ${ANSI_BOLD}[SERVICE_]:${ANSI_END} $*"
    ;;
  esac
}

inform 0 "${1:-4} workers available."

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export PYTHONPATH=/home/noam/Work_spaces/Personal/chronicle

set -euo pipefail
stty -echoctl

SCRIPT_DIR="$(realpath "$(dirname "$0")")"
CHRONICLE_WEB_UI="${SCRIPT_DIR}/chronicle_web_ui"
CHRONICLE_BASE="${SCRIPT_DIR}/chronicle_base"
serviceUp=true

# Check directories
[[ -d "$CHRONICLE_WEB_UI" ]] || {
  inform 2 "$CHRONICLE_WEB_UI not found"
  exit 1
}
[[ -d "$CHRONICLE_BASE" ]] || {
  inform 2 "$CHRONICLE_BASE not found"
  exit 1
}

# Check commands
command -v npm >/dev/null || {
  inform 2 "npm not found"
  exit 1
}
command -v uvicorn >/dev/null || {
  inform 2 "uvicorn not found"
  exit 1
}

command -v gunicorn >/dev/null || {
  inform 2 "gunicorn not found"
  exit 1
}

# Cleanup function to kill background jobs
cleanup() {
  if $serviceUp; then
    serviceUp=false
    stty echoctl
    inform 1 "Stopping all workers..."
    pkill -P $$ || true # Kill all child processes of this script
    wait
    inform 0 "All processes terminated."
    echo -e "\n${ANSI_BOLD}════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════${ANSI_END}\n"
  fi
}

# Trap termination signals
trap cleanup SIGINT SIGTERM EXIT

# Start processes
inform 0 "Starting gunicorn server..."
gunicorn chronicle_base.main:app -k uvicorn.workers.UvicornWorker -w "${1:-4}" --log-config "${CHRONICLE_BASE}/gunicorn_log_config.ini" &
gunicorn=$!

if [ "${1:-4}" -gt 4 ]; then
  sleep 2
else
  sleep 1
fi

if ! kill -0 "$gunicorn" 2>/dev/null; then
  inform 2 "Failed to start gunicorn server."
  cleanup
  exit 1
fi

inform 0 "Starting npm development server..."
npm --prefix "$CHRONICLE_WEB_UI" run dev >/dev/null &
npm_pid=$!
sleep 0.1
if ! kill -0 "$npm_pid" 2>/dev/null; then
  inform 2 "Failed to start npm dev server."
  cleanup
  exit 1
fi

inform 0 "Serving Chronicle at: ${ANSI_BOLD}${ANSI_CYAN}${ANSI_UNDERLINE}http://localhost:3000/${ANSI_END}"

wait
