version: 1

formatters:
  colorful:
    (): chronicle_base.colorful_formatter.ColorfulFormatter
    datefmt: "%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: colorful
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [console]
    level: DEBUG
    propagate: false

root:
  handlers: [console]
  level: DEBUG
